# Generated by Django 3.2 on 2022-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='cocktail',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
