# Generated by Django 3.2 on 2022-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20220808_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='recipe',
            field=models.TextField(default='ingredients'),
            preserve_default=False,
        ),
    ]
