# Generated by Django 3.2 on 2022-08-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20220808_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
