# Generated by Django 3.2 on 2022-08-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20220818_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CocktailCategory',
        ),
    ]
