# Generated by Django 3.2 on 2022-08-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_auto_20220819_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='CocktailIngredient',
        ),
    ]
