# Generated by Django 3.2 on 2022-08-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_alter_cocktailingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_ingredients_list', to='cocktails.cocktail'),
        ),
    ]
