# Generated by Django 3.2 on 2022-08-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_alter_cocktailingredient_cocktail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='recipe',
        ),
        migrations.CreateModel(
            name='CocktailRecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=254)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_steps_list', to='cocktails.cocktail')),
            ],
        ),
    ]
