# Generated by Django 3.2 on 2022-07-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_rating',
        ),
    ]
