# Generated by Django 3.2 on 2022-07-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_review_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
